KEYWORDS={
"Biologia":{"Ecologia":["ecossistema","cadeia alimentar","bioma"],"Zoologia":["artrópode","molusco","equinodermo","cordado","réptil","mamífero","inseto"],"Genética":["gene","alelo","genótipo","fenótipo","cromossomo"],"Citologia":["célula","mitose","meiose","orgânulo","membrana plasmática"],"Fisiologia":["hormônio","sistema nervoso","digestório","respiratório"],"Evolução":["seleção natural","evolução","darwin","especiação"]},
"Matemática":{"Álgebra":["equação","sistema","polinômio","inequação"],"Geometria":["triângulo","circunferência","ângulo"],"Funções":["função","domínio","gráfico"],"Trigonometria":["seno","cosseno","tangente"],"Probabilidade":["probabilidade","evento aleatório"],"PA e PG":["progressão aritmética","progressão geométrica"]},
"História":{"Brasil Colonial":["colônia","colonial","capitanias","açúcar","escravidão"],"Brasil Imperial":["império","independência","regência","dom pedro"],"República":["república velha","era vargas","ditadura militar"],"Revoluções":["revolução francesa","revolução russa","revolução industrial"],"Guerras Mundiais":["primeira guerra","segunda guerra","guerra mundial","nazismo","fascismo"],"Guerra Fria":["guerra fria","urss","otan","muro de berlim"]},
"Geografia":{"Geografia Física":["relevo","solo","erosão","geologia"],"Hidrografia":["rio","bacia hidrográfica","aquífero","nascente","foz","afluente"],"Clima":["clima","el niño","la niña","massa de ar"],"População":["população","demografia","migração","natalidade"],"Geopolítica":["geopolítica","território","fronteira","globalização"],"Meio Ambiente":["kyoto","sustentabilidade","aquecimento global"]},
"Física":{"Cinemática":["muv","velocidade","aceleração","queda livre","torricelli"],"Dinâmica":["força","newton","atrito"],"Energia":["energia cinética","energia potencial","trabalho","potência"],"Eletricidade":["corrente elétrica","resistência","voltagem","circuito"],"Ondulatória":["onda","frequência","comprimento de onda"],"Termologia":["calor","temperatura","dilatação","termodinâmica"]},
"Química":{"Química Geral":["átomo","tabela periódica","ligação química","ácido","base","sal"],"Estequiometria":["mol","estequiometria","massa molar"],"Soluções":["solução","solubilidade","concentração","precipitação"],"Orgânica":["hidrocarboneto","álcool","aldeído","cetona"],"Eletroquímica":["pilha","eletrólise","oxidação","redução"],"Físico-Química":["entalpia","equilíbrio químico","ph","cinética química"]},
"Português":{"Gramática":["gramática","ortografia","acentuação","concordância"],"Sintaxe":["oração","período","sujeito","predicado","regência","crase"],"Semântica":["semântica","sentido","ambiguidade","polissemia"],"Literatura":["literatura","romantismo","modernismo","realismo"],"Interpretação":["interpretação","inferir","compreensão"],"Redação":["redação","argumentação","tese"]},
"Inglês":{"Interpretação":["reading","according to the text","passage"],"Gramática":["grammar","verb","adjective","preposition"],"Connectors":["although","however","therefore","despite","whereas"],"Conditionals":["conditional","unless","would"],"Reported Speech":["reported speech","indirect speech"],"Vocabulary":["meaning","synonym","vocabulary","word"]}
}
def classify(discipline,text):
    low=text.lower(); data=KEYWORDS.get(discipline,{})
    scores={t:sum(k in low for k in ks) for t,ks in data.items()}
    return max(scores,key=scores.get) if scores and max(scores.values()) else None
